portalTurnPlayer: false
portalDistance: 3
portalCooldown: 1000
blockMessages: false
lang:
  noPermission: You don't have permission to use Server Portals!
  noServerPermission: You don't have permission to use the %server% portal!
signIdentifier: server
